### ISSUE TITLE
Chrome模拟ios环境下，input获取焦点报以下错误

### ISSUE THREAD

**Issue by Damon-duan** [ftlabs/fastclick#570]
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.

at FastClick.focus (webpack-internal:///./node_modules/fastclick/lib/fastclick.js:331:18)
at FastClick.onTouchEnd (webpack-internal:///./node_modules/fastclick/lib/fastclick.js:579:9)
at HTMLBodyElement.eval (webpack-internal:///./node_modules/fastclick/lib/fastclick.js:111:38)

**Comment by fanmzdj** [comment]
I get the same error. I think that it should add this judgement when targetElement.type !== 'number'. Hope author repair it. Thanks.
```
/**
  * @param {EventTarget|Element} targetElement
  */
FastClick.prototype.focus = function(targetElement) {
  var length;

  // Issue #160: on iOS 7, some input elements (e.g. date datetime month) throw a vague TypeError on setSelectionRange. These elements don't have an integer value for the selectionStart and selectionEnd properties, but unfortunately that can't be used for detection because accessing the properties also throws a TypeError. Just check the type instead. Filed as Apple bug #15122724.
  if (deviceIsIOS && targetElement.setSelectionRange && targetElement.type.indexOf('date') !== 0 && targetElement.type !== 'time' && targetElement.type !== 'month' && targetElement.type !== 'email') {
    length = targetElement.value.length;
    targetElement.setSelectionRange(length, length);
  } else {
    targetElement.focus();
  }
};
```

**Comment by starsion** [comment]
老哥，你们都不看之前的issuse么？？？！！！
